name: build-and-deploy

on:
  push:
    branches: [ "master" ]

  # add run-button on actions tab to run manually
  workflow_dispatch:

jobs:
  build_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: jakejarvis/hugo-build-action@v0.84.3
        with:
          args: -v
      - uses: cpina/github-action-push-to-another-repository@main
        env:
          SSH_DEPLOY_KEY: ${{ secrets.SSH_PUSH_TO_FRRM_GITHUB_IO }}
        with:
          source-directory: public/
          destination-github-username: 'frrm'
          destination-repository-name: 'frrm.github.io'
          target-branch: 'master'
          commit-message: 'Update website.'
